[build]
  command = "npm run build"  # Change this if your build command is different
  publish = "dist"  # Change this to your output directory (e.g., 'build' for React, 'out' for Next.js)

[dev]
  command = "npm run dev"  # Change this if using a specific development server
  port = 8888
  targetPort = 3000  # Change to match your local dev server port

[build.environment]
  NODE_VERSION = "18"  # Change to your Node.js version if needed

[[redirects]]
  from = "/api/*"
  to = "https://your-api.example.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
