[build]
  command = ""         # No build step needed for plain HTML/CSS/JS
  publish = "."        # Publish current directory

[dev]
  command = "npx serve ."
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
